name: build

on:
  push:
    paths:
      - 'src/**'
      - 'build-*/**'
      - '.github/workflows/**.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'build-*/**'
      - '.github/workflows/**.yml'

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            autotools
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_image
            mingw-w64-x86_64-SDL2_mixer
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-nsis

      - name: Build
        run: |
          cd build-windows/
          ./autogen.sh
          ./configure
          ./go --silent --release

      - name: Bundle together
        run: |
          cd build-windows/
          bash make_release.sh

      - name: Upload output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: principia-setup.exe
          path: build-windows/principia-setup.exe

  android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends openjdk-11-jdk-headless
      - name: Build with gradle
        run: |
          cd build-android
          ./gradlew assemblerelease
      - name: Save apk artifact
        uses: actions/upload-artifact@v3
        with:
          name: principia-release-unsigned.apk
          path: build-android/principia/build/outputs/apk/release/principia-release-unsigned.apk
